### PR TITLE
Fixes to issues reported by coverity

### LINKED ISSUE #60: CID 1566397:  Null pointer dereferences  (NULL_RETURNS)
```
** CID 1566397:  Null pointer dereferences  (NULL_RETURNS)
/src/main/java/com/teragrep/k8s_01/K8SConsumer.java: 136 in com.teragrep.k8s_01.K8SConsumer.accept(com.teragrep.rlo_13.FileRecord)()


________________________________________________________________________________________________________
*** CID 1566397:  Null pointer dereferences  (NULL_RETURNS)
/src/main/java/com/teragrep/k8s_01/K8SConsumer.java: 136 in com.teragrep.k8s_01.K8SConsumer.accept(com.teragrep.rlo_13.FileRecord)()
130                             record.getFilename(),
131                             record.getStartOffset()
132                         )
133                     );
134                 }
135                 Instant instant = Instant.parse(log.getTimestamp());
>>>     CID 1566397:  Null pointer dereferences  (NULL_RETURNS)
>>>     Calling a method on null object "instant".
136                 ZonedDateTime zdt = instant.atZone(timezoneId);
137                 String timestamp = zdt.format(format);
138     
139                 LOGGER.trace(
140                         "[{}] Raw record value: {}",
141                         uuid,
```

### PR DESCRIPTION
**Pull request by StrongestNumber9**
Should fix #60, #62

### CODE REVIEW

File: src/main/java/com/teragrep/k8s_01/K8SConsumer.java [hunk 1]
```diff
@@ -287,7 +303,7 @@ public void accept(FileRecord record) {
                     .withAppName(appName)
                     .withFacility(Facility.USER)
                     .withSDElement(SDMetadata)
-                    .withMsg(new String(record.getRecord()));
+                    .withMsg(new String(record.getRecord(), Charset.defaultCharset()));
```
Comment (kortemik) [inline src/main/java/com/teragrep/k8s_01/K8SConsumer.java:306]: utf8 here

File: src/main/java/com/teragrep/k8s_01/K8SConsumer.java [hunk 2]
```diff
@@ -95,12 +96,12 @@ public void accept(FileRecord record) {
...
             try {
                 // We want to read the kubernetes log event into a POJO
-                log = gson.fromJson(new String(record.getRecord()), KubernetesLogFilePOJO.class);
+                log = gson.fromJson(new String(record.getRecord(), Charset.defaultCharset()), KubernetesLogFilePOJO.class);
             } catch (JsonParseException e) {
                 LOGGER.trace(
                         "[{}] Invalid syntax message: {}",
                         uuid,
-                        new String(record.getRecord())
+                        new String(record.getRecord(), Charset.defaultCharset())
```
Comment (kortemik) [inline src/main/java/com/teragrep/k8s_01/K8SConsumer.java:104]: utf8 here

File: src/main/java/com/teragrep/k8s_01/K8SConsumer.java [hunk 3]
```diff
@@ -122,7 +123,7 @@ public void accept(FileRecord record) {
                 LOGGER.debug(
                         "[{}] Can't parse this properly: {}",
                         uuid,
-                        new String(record.getRecord())
+                        new String(record.getRecord(), Charset.defaultCharset())
```
Comment (kortemik) [inline src/main/java/com/teragrep/k8s_01/K8SConsumer.java:126]: utf8 here

**Review by kortemik — CHANGES_REQUESTED** [review]

File: src/main/java/com/teragrep/k8s_01/KubernetesLogReader.java [hunk 4]
```diff
@@ -58,16 +57,23 @@ public static void main(String[] args) throws IOException {
             );
             return;
         }
-        catch (InvalidConfigurationException e) {
+        catch (Exception e) {
             LOGGER.error(
-                    "Failed to validate config 'etc/config.json':",
+                    "Unknown exception while handling config:",
```
Comment (kortemik) [inline src/main/java/com/teragrep/k8s_01/KubernetesLogReader.java:62]: remove unknown

**Review by kortemik — CHANGES_REQUESTED** [review]

**Review by kortemik — APPROVED** [review]
APR ON
